"""remainder tiems

Revision ID: 44e6ba255ce8
Revises: 4c410787ee3a
Create Date: 2025-02-27 18:49:18.641816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44e6ba255ce8'
down_revision = '4c410787ee3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=mysql.TIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=sa.Date(),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
