"""updated the whole models and authentications

Revision ID: 4c410787ee3a
Revises: 75b93e1f523d
Create Date: 2025-02-27 18:47:44.081100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c410787ee3a'
down_revision = '75b93e1f523d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority_enum', native_enum=False), server_default='medium', nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('Completed', 'Almost finished', 'In progress', 'Not started', name='status_enum', native_enum=False), server_default='Not started', nullable=False))
        batch_op.add_column(sa.Column('reminder_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('status')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
