"""removed the almost finished status

Revision ID: 6dc6e2b7d281
Revises: 44e6ba255ce8
Create Date: 2025-03-17 11:23:42.724176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dc6e2b7d281'
down_revision = '44e6ba255ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Enum('Completed', 'In progress', 'Not started', name='status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'Not started'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Completed', 'In progress', 'Not started', name='status_enum', native_enum=False),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("'Not started'"))

    # ### end Alembic commands ###
